INSERT INTO  silver.erp_CUST_AZ12(CID, BDATE, GEN)

SELECT
  CASE WHEN CID LIKE '%NAS%' THEN SUBSTRING(TRIM(CID), 4,LEN(CID)) 
  ELSE CID
  END AS CID,
  CASE WHEN BDATE>GETDATE() THEN NULL
  ELSE BDATE
  END AS BDATE,
  CASE WHEN UPPER(TRIM(GEN)) IN ('F','Female') THEN 'Female'
	   WHEN UPPER(TRIM(GEN)) IN('M', 'Male') THEN 'Male'
       ELSE 'Other'
  END AS GEN

  FROM bronze.erp_CUST_AZ12;

